### ISSUE TITLE
数据集访问不到

### ISSUE THREAD

**Issue by liuheng0111** [AIDC-AI/Ovis#1]
![image](https://github.com/user-attachments/assets/9532858e-52f6-45eb-bc6e-1f1b72e5a8cc)
数据集访问不到了，要怎么下载呢？

**Comment by runninglsy** [comment]
Could you provide the specific Huggingface URL that is not accessible?

**Comment by liuheng0111** [comment]
现在可以打开了，下载下来后ovis_cc12m.z01， ovis_cc12m.z02 ovis_cc12m.zip这些文件要怎么解压呢？
![image](https://github.com/user-attachments/assets/d3d1d399-9491-45d6-8ca5-eae2c71f1a42)

**Comment by runninglsy** [comment]
You may consider trying the method outlined [here](https://askubuntu.com/a/751924).

**Comment by liuheng0111** [comment]
数据集不全，有几个找不到，比如pixelprose-14m    wikipedia-348k   ocr-469k

**Comment by runninglsy** [comment]
We have uploaded these files. Please check them out.
