### ISSUE TITLE
> We have uploaded the images for `ai2d-mc-15k` to [Huggingface](https://huggingface.co/datasets/AIDC-AI/Ovis-dataset/blob/main/images/ai2d-mc-15k.zip).

### ISSUE THREAD

**Issue by liuheng0111** [AIDC-AI/Ovis#11]
> We have uploaded the images for `ai2d-mc-15k` to [Huggingface](https://huggingface.co/datasets/AIDC-AI/Ovis-dataset/blob/main/images/ai2d-mc-15k.zip).
> 
> The images for `docmatix-si-900k` are available from their original source, [Huggingface](https://huggingface.co/datasets/HuggingFaceM4/Docmatix).

@runninglsy Thank you for your response. Does the docmatic-si-900k use data or PDF? In the data, there is a list of up to 4 images, but your docmatic-si-900k images are all single images. It seems that the images do not match up. Also, I noticed that the conversations in the data don't match yours. Could you please advise me on how to process it to obtain the same dataset as yours?

_Originally posted by @liuheng0111 in https://github.com/AIDC-AI/Ovis/issues/9#issuecomment-2301147363_

**Comment by runninglsy** [comment]
We have uploaded docmatix-si-images to https://huggingface.co/datasets/AIDC-AI/Ovis-dataset/tree/main/images.
