### ISSUE TITLE
How to finetune the model？

### ISSUE THREAD

**Issue by cyj95** [AIDC-AI/Ovis#16]
any script for fully finetuning and lora finetuning?

**Comment by cyj95** [comment]
btw, demo is down.
https://www.modelscope.cn/search?search=paligemma

**Comment by runninglsy** [comment]
You can modify the parameters `ovis_pretrained_path` and `dataset_names` in the following script to finetune Ovis1.5: https://github.com/AIDC-AI/Ovis/blob/main/scripts/v1_5/Ovis1.5-Llama3-8B-S3.sh. Specifically, `ovis_pretrained_path` should be set to the local directory of Ovis 1.5 checkpoints (which can be downloaded from https://huggingface.co/AIDC-AI/Ovis1.5-Llama3-8B/tree/main).
