### ISSUE TITLE
about license

### ISSUE THREAD

**Issue by ecnuycxie** [AIDC-AI/Ovis#17]
Thanks for your excellent work and your effort on sharing the code.

In the part of license, "The project is licensed under the Apache 2.0 License and is restricted to uses that comply with the license agreements of Qwen, Llama3, Gemma2, Clip, and Siglip."

Should I adhere to the Qwen license when using the Ovis1.5-Llama3-8B model?

looking forward to your response!

**Comment by ecnuycxie** [comment]
@runninglsy  loking forward to you response

**Comment by runninglsy** [comment]
Thank you for your interest in our work.
When using the Ovis1.5-Llama3-8B model, you should adhere to the Llama3 and Siglip licenses.
When using the Ovis1.5-Gemma2-9B model, you should adhere to the Gemma2 and Siglip licenses.
