### ISSUE TITLE
The size of tensor a (3084) must match the size of tensor b (3085) at non-singleton dimension 3

### ISSUE THREAD

**Issue by longkeyy** [AIDC-AI/Ovis#18]
macos 14.6.1  M1

import os

os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
os.environ["ACCELERATE_USE_MPS_DEVICE"] = "True"

from PIL import Image
from transformers import AutoModelForCausalLM
import torch

torch.device('cuda' if torch.cuda.is_available() else 'mps')

# load model
model = AutoModelForCausalLM.from_pretrained("AIDC-AI/Ovis1.6-Gemma2-9B",
                                             device_map="mps",
                                             torch_dtype=torch.float32,
                                             multimodal_max_length=8192,
                                             trust_remote_code=True)

text_tokenizer = model.get_text_tokenizer()
visual_tokenizer = model.get_visual_tokenizer()

# enter image path and prompt
# image_path = input("Enter image path: ")
image_path = 'WechatIMG3742.jpg'
image = Image.open(image_path)
# text = input("Enter prompt: ")
text = '''从内容中抽取文本''
query = f'<image>\n{text}'

# format conversation
prompt, input_ids, pixel_values = model.preprocess_inputs(query, [image])
attention_mask = torch.ne(input_ids, text_tokenizer.pad_token_id)
input_ids = input_ids.unsqueeze(0).to(device=model.device)
attention_mask = attention_mask.unsqueeze(0).to(device=model.device)
pixel_values = [pixel_values.to(dtype=visual_tokenizer.dtype, device=visual_tokenizer.device)]

# generate output
with torch.inference_mode():
    gen_kwargs = dict(
        max_new_tokens=1024,
        do_sample=False,
        top_p=None,
        top_k=None,
        temperature=None,
        repetition_penalty=None,
        eos_token_id=model.generation_config.eos_token_id,
        pad_token_id=text_tokenizer.pad_token_id,
        use_cache=True
    )
    output_ids = model.generate(input_ids, pixel_values=pixel_values, attention_mask=attention_mask, **gen_kwargs)[0]
    output = text_tokenizer.decode(output_ids, skip_special_tokens=True)
    print(f'Output:\n{output}')

=====================================================

PYTORCH_ENABLE_MPS_FALLBACK=1 ACCELERATE_USE_MPS_DEVICE=true python demo.py
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:12<00:00,  2.57s/it]
/Users/a/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py:1562: UserWarning: The operator 'aten::isin.Tensor_Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
  and torch.isin(elements=eos_token_tensor, test_elements=pad_token_tensor).any()
Traceback (most recent call last):
  File "/Users/a/PycharmProjects/Ovis/demo.py", line 51, in <module>
    output_ids = model.generate(input_ids, pixel_values=pixel_values, attention_mask=attention_mask, **gen_kwargs)[0]
  File "/Users/a/.cache/huggingface/modules/transformers_modules/AIDC-AI/Ovis1.6-Gemma2-9B/24af34ed0ef0c909e90db50c1762ce0b7ac66f00/modeling_ovis.py", line 596, in generate
    return self.llm.generate(inputs=None, inputs_embeds=inputs_embeds, attention_mask=attention_mask, **kwargs)
  File "/Users/a/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/a/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/Users/a/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 2975, in _sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/longkeyy/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py", line 1092, in prepare_inputs_for_generation
    attention_mask = _prepare_4d_causal_attention_mask_with_cache_position(
  File "/Users/longkeyy/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py", line 102, in _prepare_4d_causal_attention_mask_with_cache_position
    padding_mask = causal_mask[:, :, :, :mask_length] + attention_mask[:, None, None, :]
RuntimeError: The size of tensor a (3084) must match the size of tensor b (3085) at non-singleton dimension 3

**Comment by runninglsy** [comment]
The error is due to a missing image placeholder. You can try:

`query = f'<image>\n{text}'`
