### ISSUE TITLE
What does IMAGE_INDICATOR_IDS mean?

### ISSUE THREAD

**Issue by SamaelChen** [AIDC-AI/Ovis#21]
I don't really understand the IMAGE_INDICATOR_IDS stands for what

**Comment by runninglsy** [comment]
In Ovis1.6, a high-resolution image is partitioned into several sub-images. The `IMAGE_INDICATOR_IDS` are utilized in the function [`construct_image_placeholders`](https://github.com/AIDC-AI/Ovis/blob/main/ovis/model/visual_tokenizer/base_visual_tokenizer.py#L96) to denote key points in the sequence of visual tokens for an image, as well as to indicate the grid structure of the partition.

The `IMAGE_INDICATOR_IDS` serve the following purposes:

- `IMAGE_INDICATOR_IDS[0]`: Marks the beginning of an image
- `IMAGE_INDICATOR_IDS[1]`: Indicates the start of a partition
- `IMAGE_INDICATOR_IDS[2]`: Represents a column separator in the grid
- `IMAGE_INDICATOR_IDS[3]`: Represents a row separator in the grid
- `IMAGE_INDICATOR_IDS[4]`: Marks the end of an image
