### ISSUE TITLE
When will the 27B Gemma version model be released?

### ISSUE THREAD

**Issue by ALFONSOBUGRA** [AIDC-AI/Ovis#34]
Hi,

I saw the comment that the 27b Gemma version will be released in issues as soon as the last days of this month in the issues. What is the situation with this version? And I wanna fine-tune the model with ms-swift. Will you prepare(publish) a guideline for fine-tuning? Or recommend any guidelines? 

Thanks for the model. It's an awesome model for my graduation project. Thanks for that.

**Comment by runninglsy** [comment]
Thank you for your interest in Ovis. We have just released [Ovis1.6-Gemma2-27B](https://huggingface.co/AIDC-AI/Ovis1.6-Gemma2-27B). For fine-tuning with ms-swift, please refer to the ms-swift project documentation for guidance.

**Comment by ALFONSOBUGRA** [comment]
Thanks for the answer. It's one of the awesome MLLMs.
