### ISSUE TITLE
The training strategy in the Ablation Study

### ISSUE THREAD

**Issue by ruxin123** [AIDC-AI/Ovis#6]
Thank you for your work. I am impressed by the significant improvement demonstrated in the Ablation Study. As mentioned in the paper, you used the same model and dataset, but the training strategy appears to be different. You utilized the training strategy of LLaVA 1.5 for training the MLP connector. To clarify, does this mean that you only trained the MLP during the pretraining stage, and then trained both the MLP and LLM during the SFT (Supervised Fine-Tuning) stage?

**Comment by runninglsy** [comment]
Thanks for your interest. Yes, since the training strategy is closely intertwined with architectural design, we fully adhere to the training approach detailed in the LLaVA paper.
