### ISSUE TITLE
有没有完整的数据集

### ISSUE THREAD

**Issue by liuheng0111** [AIDC-AI/Ovis#7]
hi，很多数据不好下载，请问后续会不会把图片也开源出来？

**Comment by runninglsy** [comment]
由于图片数量众多、来源广泛，我们无计划提供所有图片的打包下载，请根据 https://github.com/AIDC-AI/Ovis?tab=readme-ov-file#dataset 中的image source下载图片。

**Comment by liuheng0111** [comment]
图片下载遇到的一些问题：

**Comment by liuheng0111** [comment]
图片下载遇到的一些问题，docmatix-si-900k.jsonl 这里的图片路径怎么和huggingface上解析出来的parquet二进制图片对应上呢？
