### ISSUE TITLE
Some dataset can not download

### ISSUE THREAD

**Issue by liuheng0111** [AIDC-AI/Ovis#9]
有几个数据集没办法下载， AI2D(image_support和images图片有区别吗？image_support图片怎么获得？),；docmatix-si-900k.json 图片是怎么得来的，是pdf变成图片吗，是否可提供处理脚本？

**Comment by runninglsy** [comment]
We have uploaded the images for `ai2d-mc-15k` to [Huggingface](https://huggingface.co/datasets/AIDC-AI/Ovis-dataset/blob/main/images/ai2d-mc-15k.zip).

The images for `docmatix-si-900k` are available from their original source, [Huggingface](https://huggingface.co/datasets/HuggingFaceM4/Docmatix).

**Comment by liuheng0111** [comment]
> We have uploaded the images for `ai2d-mc-15k` to [Huggingface](https://huggingface.co/datasets/AIDC-AI/Ovis-dataset/blob/main/images/ai2d-mc-15k.zip).
> 
> The images for `docmatix-si-900k` are available from their original source, [Huggingface](https://huggingface.co/datasets/HuggingFaceM4/Docmatix).

@runninglsy Thank you for your response. Does the docmatic-si-900k use data or PDF? In the data, there is a list of up to 4 images, but your docmatic-si-900k images are all single images. It seems that the images do not match up. Also, I noticed that the conversations in the data don't match yours. Could you please advise me on how to process it to obtain the same dataset as yours?
